# Generated by Django 5.0.4 on 2024-06-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('surname', models.CharField(blank=True, max_length=32, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=32, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailshot_datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('FD', 'Fail')], max_length=2)),
                ('response', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Mailshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
