# Generated by Django 5.0.4 on 2024-06-23 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('mailshots', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailshotPeriodicTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.periodictask')),
                ('frequency', models.CharField(choices=[('DAILY', 'every day'), ('WEEKLY', 'every week'), ('MONTHLY', 'every_month')], max_length=8)),
                ('is_new', models.BooleanField(default=True)),
                ('clients', models.ManyToManyField(to='mailshots.client')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailshots.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
        migrations.AlterField(
            model_name='log',
            name='mailshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailshots.mailshotperiodictask'),
        ),
        migrations.DeleteModel(
            name='Mailshot',
        ),
    ]
