# Generated by Django 5.0.4 on 2024-06-23 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('mailshots', '0003_mailshotperiodictask_alter_log_mailshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Информация об отправке', 'verbose_name_plural': 'Информация об отправках'},
        ),
        migrations.AlterModelOptions(
            name='mailshotperiodictask',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='mailshotperiodictask',
            name='defined_name',
            field=models.CharField(default='wchada', max_length=100, verbose_name='Имя, установленное пользователем'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавивший пользователь'),
        ),
        migrations.AlterField(
            model_name='log',
            name='mailshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailshots.mailshotperiodictask', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='log',
            name='mailshot_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response',
            field=models.CharField(max_length=16, verbose_name='Ответ сервиса отправки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('OK', 'Ok'), ('FD', 'Fail')], max_length=2, verbose_name='Статус отправки'),
        ),
        migrations.AlterField(
            model_name='mailshotperiodictask',
            name='clients',
            field=models.ManyToManyField(to='mailshots.client', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='mailshotperiodictask',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'every day'), ('WEEKLY', 'every week'), ('MONTHLY', 'every_month')], max_length=8, verbose_name='Частота рассылки'),
        ),
        migrations.AlterField(
            model_name='mailshotperiodictask',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Рассылка новая'),
        ),
        migrations.AlterField(
            model_name='mailshotperiodictask',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailshots.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailshotperiodictask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создавший пользователь'),
        ),
        migrations.AddConstraint(
            model_name='mailshotperiodictask',
            constraint=models.UniqueConstraint(fields=('defined_name', 'user'), name='unique_mailshot_name_for_user'),
        ),
    ]
