# Generated by Django 5.0.4 on 2024-06-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailshots', '0004_alter_client_options_alter_log_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailshotperiodictask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mailshotperiodictask',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
