# Generated by Django 5.0.4 on 2024-06-24 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailshots', '0005_alter_client_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email', 'user'), name='unique_client_for_user'),
        ),
    ]
