# Generated by Django 5.0.4 on 2024-06-25 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailshots', '0007_alter_mailshotperiodictask_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailshotperiodictask',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'every day'), ('WEEKLY', 'every week'), ('MONTHLY', 'every_month')], default='DAILY', max_length=8, verbose_name='Частота рассылки'),
        ),
    ]
