# Generated by Django 5.0.4 on 2024-06-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='содержимое статьи')),
                ('image', models.ImageField(upload_to='blog/images/', verbose_name='фото')),
                ('views_amount', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
